<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GrocerySense.Data\GrocerySense.Data.csproj" />
    <ProjectReference Include="..\GrocerySense.Integrations\GrocerySense.Integrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

